/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ksiazkakucharska;

import com.itextpdf.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import static ksiazkakucharska.CKsiazkaKucharska.PolaczenieZBaza;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import org.slf4j.*;

/**
 *
 * @author Dagmara
 */
public class CPrzepis extends javax.swing.JFrame {
    private int id;
    private String tytul;
    
    /**
     * Creates new form CPrzepis
     */
    public CPrzepis() {
        initComponents();
    }
    /*
    recipe display
    */
    public void pokazPrzepis(int id, String tytul, String tresc, List<String> skladniki, List<String> ilosci){
        tytulGP.setText(tytul);
        //Collections.reverse(skladniki);
        //Collections.reverse(ilosci);
        for(String s:skladniki) {
            PTskladnikiGP.append(s);
            PTskladnikiGP.append("\n");
        }
        for(String i:ilosci) {
            PTiloscGP.append(i);            
            PTiloscGP.append("\n");
        }
        PTwykonanieGP.setText(tresc);
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tytulGP = new javax.swing.JLabel();
        SkladnikiGP = new javax.swing.JLabel();
        WykonanieGP = new javax.swing.JLabel();
        Usun = new javax.swing.JButton();
        IloscGP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PTiloscGP = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        PTskladnikiGP = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        PTwykonanieGP = new javax.swing.JTextArea();
        Edytuj = new javax.swing.JButton();
        GenerujListeZakupow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Przepis");
        setResizable(false);

        tytulGP.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        tytulGP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytulGP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SkladnikiGP.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        SkladnikiGP.setText("Składniki:");

        WykonanieGP.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        WykonanieGP.setText("Wykonanie:");

        Usun.setText("Usuń");
        Usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunActionPerformed(evt);
            }
        });

        IloscGP.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        IloscGP.setText("Ilosc:");

        PTiloscGP.setColumns(20);
        PTiloscGP.setLineWrap(true);
        PTiloscGP.setRows(5);
        PTiloscGP.setSelectionColor(new java.awt.Color(255, 0, 204));
        jScrollPane1.setViewportView(PTiloscGP);

        PTskladnikiGP.setColumns(20);
        PTskladnikiGP.setLineWrap(true);
        PTskladnikiGP.setRows(5);
        PTskladnikiGP.setSelectionColor(new java.awt.Color(255, 0, 204));
        jScrollPane2.setViewportView(PTskladnikiGP);

        PTwykonanieGP.setColumns(20);
        PTwykonanieGP.setLineWrap(true);
        PTwykonanieGP.setRows(5);
        PTwykonanieGP.setSelectionColor(new java.awt.Color(255, 0, 204));
        jScrollPane3.setViewportView(PTwykonanieGP);

        Edytuj.setText("Edytuj");
        Edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytujActionPerformed(evt);
            }
        });

        GenerujListeZakupow.setText("Generuj listę zakupów");
        GenerujListeZakupow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerujListeZakupowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tytulGP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IloscGP)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SkladnikiGP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WykonanieGP)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Edytuj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Usun, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GenerujListeZakupow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tytulGP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SkladnikiGP)
                    .addComponent(WykonanieGP)
                    .addComponent(IloscGP))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edytuj)
                    .addComponent(GenerujListeZakupow))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    removing the recipe
    */
    private void UsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunActionPerformed
        Connection polaczenie = PolaczenieZBaza();
        try{
            polaczenie.createStatement().executeUpdate("DELETE FROM `skladniki` WHERE PrzepID="+this.id+"");
            polaczenie.createStatement().executeUpdate("DELETE FROM `przepis` WHERE ID="+this.id+"");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        this.hide();
    }//GEN-LAST:event_UsunActionPerformed
/*
    edition of the recipe
    */
    private void EdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytujActionPerformed
        Connection polaczenie = PolaczenieZBaza();
        try{
            Statement stm = polaczenie.createStatement();
            int id = this.id;
            stm.executeUpdate("UPDATE `przepis` SET Tresc='"+PTwykonanieGP.getText()+"' WHERE ID="+this.id);
            String skladniki[] = PTskladnikiGP.getText().split("\\r?\\n");
            String ilosci[] = PTiloscGP.getText().split("\\r?\\n");
            int n = skladniki.length;
            stm.executeUpdate("DELETE FROM `skladniki` WHERE PrzepID="+this.id);
            for(int i=0; i<n; i++){
                stm.executeUpdate("INSERT INTO `skladniki` (PrzepID, Nazwa, Ilosc) VALUES ("+id+",'"+skladniki[i]+"','"+ilosci[i]+"')");
            }
            stm.close();
            this.hide();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }        
    }//GEN-LAST:event_EdytujActionPerformed
/*
    generating a shopping list
    */
    private void GenerujListeZakupowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerujListeZakupowActionPerformed
        try {
            PdfWriter pdfWriter = new PdfWriter("lista.pdf");
            PdfDocument pdfDocument = new PdfDocument(pdfWriter);
            Document doc = new Document(pdfDocument);
            String skladniki[] = PTskladnikiGP.getText().split("\\r?\\n");
            String ilosci[] = PTiloscGP.getText().split("\\r?\\n");
            for(int i=0; i<skladniki.length;i++){
                doc.add(new Paragraph(skladniki[i]+" - "+ilosci[i]));
            }
            doc.close();
        }
        catch(IOException e){
            e.printStackTrace();
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPrzepis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GenerujListeZakupowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPrzepis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPrzepis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPrzepis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPrzepis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPrzepis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edytuj;
    private javax.swing.JButton GenerujListeZakupow;
    private javax.swing.JLabel IloscGP;
    private javax.swing.JTextArea PTiloscGP;
    private javax.swing.JTextArea PTskladnikiGP;
    private javax.swing.JTextArea PTwykonanieGP;
    private javax.swing.JLabel SkladnikiGP;
    private javax.swing.JButton Usun;
    private javax.swing.JLabel WykonanieGP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel tytulGP;
    // End of variables declaration//GEN-END:variables
}
